version: '3.3'

services:

  # MySQL
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "33061:3306"

  redis:
    image: redis


  # Health
  health:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        LARAVEL_TAG: v5.6.12
        LARAVEL_HEALTH_VERSION: v0.9.16
    restart: "on-failure"
    ports:
      - "8087:8087"
    depends_on:
      - mysql
    volumes:
      - ./storage:/health/repository/storage
      - ./custom_health_conf:/health/repository/config/health:ro
    environment:
      - APP_URL=http://localhost:8087/
      - APP_DEBUG=false
      - REDIS_HOST=redis
      # - PUSHER_APP_ID=
      # - PUSHER_APP_KEY=
      # - PUSHER_APP_SECRET=
      # - SLACK_WEBHOOK_URL=
